name: oloom_noh
description: "علوم نهم – استاد ویسی: اپلیکیشن آموزشی علوم تجربی پایه نهم"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_messaging: ^14.7.15
  firebase_analytics: ^10.8.5

  # State management
  provider: ^6.1.2

  # PDF
  syncfusion_flutter_pdfviewer: ^24.2.8

  # عکس
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  cached_network_image: ^3.3.1

  # ذخیره‌سازی محلی
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # نمودار
  fl_chart: ^0.66.2

  # شبکه
  http: ^1.2.1

  # ابزار
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
